### ISSUE TITLE
Named exports

### ISSUE THREAD

**Issue by guybedford** [css-modules/jspm-demo#1]
Was so awesome to see this today! Really nice work.

Wondering if it is worth making the exports object for the stylesheet named ES6 exports like:

``` javascript
import {lol, another} from './main.css!'
```

Alternatively I guess we could always do both, serving the names under both `default` and as named exports.

**Comment by geelen** [comment]
Sorry, I missed this when you posted it. I think we covered this on gitter yesterday, but for the record, my main thinking is to avoid a third place to type the word (CSS, import & usage) instead of just `.lol` in the CSS and `style.lol` in the usage. And it keeps a more direct correlation with webpack and browserify using `require` syntax, which I think is good for bringing in newcomers.
